version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
        - ${POSTGRES_PORT}:5432
    env_file:
        - .env
    volumes:
        - ./host-folder/:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    env_file:
      - .env