export const USERS = [
    {
        login:'test-user-1',
        email:'example-1@example.com',
        password:'$2b$10$kJd7KeBdJxeDSVK.U9/Y1.xIoh7mF3PIzn8i3Zmd/uyF0h4CzgWfu',
        isActive:true,
        role:1
    },
    {
        login:'test-user-2',
        email:'example-2@example.com',
        password:'$2b$10$iWafYQHgkcbF5ggX3GGT.upYVdttOEiXFy3PxWHMPTf.V.I1KC55m',
        isActive:true,
        role:0
    },
    {
        login:'test-user-3',
        email:'example-3@example.com',
        password:'$2b$10$A7EGf54gIkUUbJiSPKIyiOsJ3PpVk1RlUr3MQHObhVTlLDNdYA.P2',
        isActive:true,
        role:0
    },
    {
        login:'test-user-4',
        email:'example-4@example.com',
        password:'$2b$10$C4yN4BL0wU2mgitltLO62euQAhbwohH8ayuG/xr5S2ibofpsJl4lK',
        isActive:true,
        role:0
    },
    {
        login:'test-user-5',
        uuid:'ee4e8818-3eb0-47a8-9925-1e7cec52fa0e',
        email:'example-5@example.com',
        password:'$2b$10$fBHUKFocpTPnfzSGAnN1KuuKqlc0JUUmqt6oFREOT5YSZeVuDeP0K',
        isActive:false,
        role:0
    },
]

export const PROXIES = [
    {
        type:0,
        private:false,
        isActive:false,
        host:'185.103.246.59',
        port:8080,
        country:'',
    },
    {
        type:0,
        private:false,
        isActive:false,
        host:'84.42.63.99',
        port:3128,
        country:'',
    },
    {
        type:0,
        private:false,
        isActive:false,
        host:'78.29.81.187',
        port:8080,
        country:'',
    },
    {
        type:0,
        private:false,
        isActive:false,
        host:'194.190.136.35',
        port:8080,
        country:'',
    },
    {
        type:0,
        private:false,
        isActive:false,
        host:'80.87.197.12',
        port:3128,
        country:'',
    },
    {
        type:0,
        private:false,
        isActive:false,
        host:'81.163.97.238',
        port:8080,
        country:'',
    },
    {
        type:0,
        private:false,
        isActive:false,
        host:'178.167.25.212',
        port:8080,
        country:'',
    },
    {
        type:0,
        private:false,
        isActive:false,
        host:'188.166.254.252',
        port:8080,
        country:'',
    },
    {
        type:0,
        private:false,
        isActive:false,
        host:'77.238.138.171',
        port:80,
        country:'',
    },
    {
        type:0,
        private:false,
        isActive:false,
        host:'195.189.98.112',
        port:3128,
        country:'',
    },
]